### ISSUE TITLE
Can you infer housing construction from housing sales data?

### ISSUE THREAD

**Issue by timsehn** [dolthub/data-analysis#11]
NIMBY (Not in my backyard) vs YIMBY (yes in my backyard) is a current thing.

Can we use "first sale" data in the us-housing-price-v2 database:

https://www.dolthub.com/repositories/dolthub/us-housing-prices-v2

to gauge which places are building more houses, even relative to other places in the database.

**Comment by rl1987** [comment]
WIP: https://github.com/dolthub/data-analysis/pull/16

**Comment by rl1987** [comment]
https://www.dolthub.com/blog/2022-12-08-nimby-yimby/
