### ISSUE TITLE
Data structures changed

### ISSUE THREAD

**Issue by maurhub** [dolthub/data-analysis#38]
Hi!, I was trying to build a Data Analysis test using the data sets from the health insurance USA's companies, but all the data sources I tested did not work. I spent a few hours debugging and trying to get it working, but the data structure is pretty different from what it was in 2022. I tested all the downloaders from the repo, some of those didn't work, others did (with minor adjustments on the URLs) download the data json URLs, but the giant jsons structure that were parsed via those URLs didn't match with what the dialysis parser is expecting. 

Any clues?

**Comment by alecstein** [comment]
Hey, totally understandable and thanks for reaching out. I need a little more context:

> URLs didn't match with what the dialysis parser is expecting.

This is my clue -- are you trying to run the `dialysis` example? That hasn't been updated in a while (we've gone through a lot of breaking changes with our tool) -- so it might be busted. Do you mind telling me your exact workflow?

1. What script(s) were you trying to run?
2. What did you see (error wise)?

**Comment by alecstein** [comment]
Actually it's a good chance for me to update that example.

So here's what I did.

I went to `/downloaders/` and removed the old `uhc_data.db` and then did

```> python uhc.py
Downloading UHC's blob file containing all URLs...
Finished.
Fetching URLs and their sizes...
Total filesize in GB: 20662
```

Now I have a SQLite database of all the files in UHC. So I'm gonna export some fraction of them

```sql
select url from in_network_files
where (
  size < 1000000000 and 
  size > 10000000 and 
  url like '%in-network%' and 
  lower(url) not like '%dental%' and
  lower(url) not like '%vision%' and
  lower(url) not like '%ndc%'
)
order by size;
```

Then I exported those URLs to `urls.txt` and now I'm running `dialysis.sh`. I'll get back to you with the results.

**Comment by alecstein** [comment]
When I check the `log.txt` I get a list of errors like

```
Failed for "https://uhc-tic-mrf.azureedge.net/public-mrf/2023-01-01/2023-01-01_UnitedHealthcare-of-Utah--Inc-_Insurer_PPO-NDC_PPO-NDC_in-network-rates.json.gz"
No connection adapters were found for '"https://uhc-tic-mrf.azureedge.net/public-mrf/2023-01-01/2023-01-01_UnitedHealthcare-of-Utah--Inc-_Insurer_PPO-NDC_PPO-NDC_in-network-rates.json.gz"'
```

I've never seen this before, so let me look into it.

**Comment by maurhub** [comment]
Alec, thanks for looking into this.
What I did was exactly that. Removed the db, then ran the downloader for UHC (and tried many others), then exported a fraction of those SQLite rows into urls.txt, then ran dialisys.sh. I didn't get the no connection adapters were found error, but I didn't got results either. 

My understanding with UHC is they changed their data so now they have files which are just metadata of other files, then the downloader is downloading those meta data files, and the processor doesn't understand them. 

I did another try on that , trying to download the in-network files from the metadata json files, and insert their urls in the SQLite, then parse those urls with the processor, but wasn't lucky either. 

I did notice though that not every file from their index is a metadata file, there are some big files that I assume have pricings, but I got different errors on those , mostly like 'incomplete json' or connection errors.

**Comment by alecstein** [comment]
Go ahead and try to run `process_dialysis.py` now. It should be working.

I went ahead and made this python script a package so I'm not sure if that changes things. You may need to go to `mrfutils/` (the main folder) and do `pip install -e ./`. But only try this if you get an import error.

(Edit: yea you will need to do this.)

From there, `dialysis.sh` should run. Feel free to run it on a test file before running the script just to make sure you get the debug output. Should look like:

<img width="1142" alt="image" src="https://user-images.githubusercontent.com/16236421/210705044-27b665ea-385c-425b-893b-77836dc65f8c.png">

**Comment by maurhub** [comment]
Weird, did both ``pip install -e ./`` in /mrfutils , seemed to be ok:
``Defaulting to user installation because normal site-packages is not writeable
Obtaining file:///Users/maurolopez/Desktop/data-analysis/transparency-in-coverage/python/mrfutils
Installing collected packages: mrfutils
  Running setup.py develop for mrfutils
Successfully installed mrfutils``

But then when I ```python3 process_dialysis.py```, it breaks because:
``Traceback (most recent call last):
  File "process_dialysis.py", line 1, in <module>
    from mrfutils import json_mrf_to_csv
ModuleNotFoundError: No module named 'mrfutils'``

This was tested in a just cloned repo

**Comment by alecstein** [comment]
Oh god ok let me try that.

**Comment by alecstein** [comment]
My steps:

```
~ git clone https://github.com/dolthub/data-analysis.git
Cloning into 'data-analysis'...
remote: Enumerating objects: 2828, done.
remote: Counting objects: 100% (379/379), done.
remote: Compressing objects: 100% (222/222), done.
remote: Total 2828 (delta 181), reused 329 (delta 150), pack-reused 2449
Receiving objects: 100% (2828/2828), 36.62 MiB | 2.94 MiB/s, done.
Resolving deltas: 100% (1318/1318), done.
```

Then

```
cd data-analysis/transparency-in-coverage/python/mrfutils/  
```

Then

```
conda create -n test python=3.9 
```

to make sure I have the right python installed.

Then 
```
pip install -e .
```

to install the package, followed by

```
pip install -r requirements.txt
```

in the same folder.

There is one last thing which is this uses a fast C backend to do the JSON parsing -- I recommend installing it with 

```brew install yajl```

If not, you can comment out this line in `mrfutils.py`:

`mrfutils.py`
```
# You can remove this if necessary, but be warned
# Right now this only works with python 3.9/3.10
assert ijson.backend in ('yajl2_c', 'yajl2_cffi')
```

The final step was to confirm that the dialysis script indeed ran:

```
python process_dialysis.py --url "https://uhc-tic-mrf.azureedge.net/public-mrf/2023-01-01/2023-01-01_Neighborhood-Health-Partnership--Inc-_Insurer_PPO-NDC_PPO-NDC_in-network-rates.json.gz" --npi dialysis_npis.csv --out dialysis_csv
```

and it does.

**Comment by maurhub** [comment]
The virtual environment was the key, I wasn't creating one and my modules where installed to a weird spot.
Not it works, thanks!
